
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bryan
 */
public class jfrmGuia_3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmGuia_3.class.getName());

    /**
     * Creates new form jfrmGuia_3
     */
    public jfrmGuia_3() {
        initComponents();
        this.setTitle("Menu principal ");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500,450);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlblPiezas = new javax.swing.JLabel();
        jlblNomPieza = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblPiezas.setText("jLabel1");

        jlblNomPieza.setBackground(new java.awt.Color(255, 255, 255));
        jlblNomPieza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblNomPieza.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jlblNomPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlblNomPieza)
                .addGap(36, 36, 36)
                .addComponent(jlblPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivos ");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Componentes del pc");

        jMenuItem5.setText("Placa base");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Procesador");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Memoria RAM");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Disco duro");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Unidad SSD");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Fuente de poder");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Fuente de video");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Tarjeta de red ");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Cooler ");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Ventilador");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Tarjeta de sonido");
        jMenuItem15.addActionListener(this::jMenuItem15ActionPerformed);
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Bateria CMOS");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Cable SATA  ");
        jMenuItem17.addActionListener(this::jMenuItem17ActionPerformed);
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Cable de Alimentación");
        jMenuItem18.addActionListener(this::jMenuItem18ActionPerformed);
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("BIOS / UEFI  ");
        jMenuItem19.addActionListener(this::jMenuItem19ActionPerformed);
        jMenu2.add(jMenuItem19);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda ");

        jMenuItem20.setText("Acerca del programa");
        jMenuItem20.addActionListener(this::jMenuItem20ActionPerformed);
        jMenu3.add(jMenuItem20);

        jMenuItem21.setText("Creditos");
        jMenuItem21.addActionListener(this::jMenuItem21ActionPerformed);
        jMenu3.add(jMenuItem21);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser selector = new JFileChooser();

int opcion = selector.showSaveDialog(this);

if (opcion == JFileChooser.APPROVE_OPTION) {
    File archivo = selector.getSelectedFile();

    JOptionPane.showMessageDialog(this,
            "Archivo guardado en:\n" + archivo.getAbsolutePath(),
            "Guardar",
            JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser selector = new JFileChooser();

int opcion = selector.showOpenDialog(this);

if (opcion == JFileChooser.APPROVE_OPTION) {
    File archivo = selector.getSelectedFile();

    JOptionPane.showMessageDialog(this,
            "Archivo seleccionado:\n" + archivo.getAbsolutePath(),
            "Abrir",
            JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de que desea salir?",
        "Salir",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
);

if (opcion == JOptionPane.YES_OPTION) {
    System.exit(0);   // Cierra el programa
}
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/cpu.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/bateriacmos.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/biosuefi.png")));
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/cablealimentacion2.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/cablesata2.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/cooler.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/discoduro2.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/fuente.png")));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/motherboard.png")));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/ram.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/tarjetared2.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/tarjetasonido.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/tarjetadevideo.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/unidadssd.png")));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        jlblPiezas.setText("");
        jlblNomPieza.setText("Procesador");
        jlblNomPieza.setForeground(Color.white);
        jlblPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("ImagenesG3/ventilador.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        JOptionPane.showMessageDialog(
    this,
    "EDITOR DE TEXTO\n\n"
    + "Versión: 1.0\n"
    + "Desarrollado por: Bryan González\n"
    + "Colegio Salesiano Don Bosco",
    "Acerca del programa",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        JOptionPane.showMessageDialog(
        this,
        "CRÉDITOS\n\n"
      + "Proyecto: Editor de Texto\n"
      + "Desarrollado por: Bryan González\n"
      + "Curso: Computación Aplicada\n"
      + "Colegio Salesiano Don Bosco\n"
      + "Año: 2026",
        "Créditos",
        JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmGuia_3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblNomPieza;
    private javax.swing.JLabel jlblPiezas;
    // End of variables declaration//GEN-END:variables
}
